### ISSUE TITLE
Error clonebot images are not allowed on Fly.io - error fly

### ISSUE THREAD

**Issue by BragnarXIX** [TheCaduceus/CloneBot_V2#72]
![2](https://user-images.githubusercontent.com/114120494/191637774-aa218e9a-5e45-4c59-8857-1e73060ee9de.jpg)
any solution?

**Comment by TheCaduceus** [comment]
**Fly.io stopped the further deployment of CloneBot V2 on their platform because of sudden increase in number of deployments, we added deployment to Fly.io because of heavy requests from users and they kept proving that CloneBot V2 is legal on Fly.io and now its users and platform's headache that what they want to do next. In the instructions given, we already told everyone to not create any issue regarding any error during deployment process:**
>7.Don't blame contributors of CloneBot V2 in case your account got suspended while using it by deploying on free services provided below! (We already provided you the details that you should follow to prevent it if you are new to this platforms) on Clever-Cloud add Credit card before deploying your bot on it, only report error which is releated with code of CloneBot V2! we don't accept problems regarding any platform on which you are going to deploy this.

**Secondly,**
>9.Aim of CloneBot V2 is not to violate any platform's TOS and hence we removed deployment support of platforms like Heroku, don't create an issue or PR for adding support of Heroku or platforms which don't allow it or if CloneBot V2 violate their TOS.

**Now if we look into the message which is shared by you then it is clearly written:**
>clonebot images are not allowed on Fly.io

**which clearly declares that CloneBot V2 is not legal on their platform, it will be better to ask those users who previously upvoted & proved CloneBot V2 legal on Fly.io @BragnarXIX **
